name = "Shallowslept"
author = "Mythoid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a22c8528f37031e4f7f7eaab385d17fddcf647efaea7124daa09fd244d7e8698"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
