name = "Shallowslept"
author = "Mythoid"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c551ad16c571bb3914ba3abd953e22a5bc53ef967f3b22b2b92cffcdfdd5c73"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
